Fix create new book
Caused by: javax.persistence.PersistenceException:
org.hibernate.PersistentObjectException: detached entity passed to persist:
ru.shishmakov.domain.Genre
ru.shishmakov.domain.Author